# Generated by Django 6.0.5 on 2026-05-22 17:10

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default=91212231234,
                max_length=12,
                validators=[accounts.validators.validate_iranian_cellphone_number],
            ),
            preserve_default=False,
        ),
    ]
