# Generated by Django 6.0.6 on 2026-06-17 11:54

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                null=True,
                unique=True,
                validators=[accounts.validators.validate_iranian_cellphone_number],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
