# Generated by Django 6.0.5 on 2026-05-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["created_date"]},
        ),
    ]
