# Generated by Django 6.0.6 on 2026-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "initiated"),
                    (3, "success"),
                    (4, "failed"),
                ],
                default=1,
            ),
        ),
    ]
